// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fdbserverfb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Records struct {
	_tab flatbuffers.Table
}

func GetRootAsRecords(buf []byte, offset flatbuffers.UOffsetT) *Records {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Records{}
	x.Init(buf, n+offset)
	return x
}

func FinishRecordsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRecords(buf []byte, offset flatbuffers.UOffsetT) *Records {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Records{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRecordsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Records) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Records) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Records) Values(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *Records) ValuesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func RecordsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RecordsAddValues(builder *flatbuffers.Builder, values flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(values), 0)
}
func RecordsStartValuesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func RecordsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
