name: gosdk test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  featuredb-unit-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-featuredb-pipeline
      cancel-in-progress: false
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
        
      - name: Run featuredb unit tests
        env:
          ACCESS_ID: ${{ secrets.SDK_ACCESS_ID }}
          ACCESS_KEY: ${{ secrets.SDK_ACCESS_KEY }}
          FEATUREDB_USERNAME: ${{ secrets.FEATUREDB_USERNAME }}
          FEATUREDB_PASSWORD: ${{ secrets.FEATUREDB_PASSWORD }}
          SDK_INSTANCE_ID: ${{ secrets.SDK_INSTANCE_ID }}
          FEATURE_SERVICE_ADDRESS: ${{ secrets.FEATURE_SERVICE_ADDRESS }}
          FEATURE_SERVICE_TOKEN: ${{ secrets.FEATURE_SERVICE_TOKEN }}
        run:
          go test -v -count=1 ./tests/test_cases/featuredb_test.go
  hologres-unit-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-hologres-pipeline
      cancel-in-progress: false
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
        
      - name: Run hologres unit tests
        env:
          ACCESS_ID: ${{ secrets.SDK_ACCESS_ID }}
          ACCESS_KEY: ${{ secrets.SDK_ACCESS_KEY }}
          SDK_INSTANCE_ID: ${{ secrets.SDK_INSTANCE_ID }}
        run:
          go test -v -count=1 ./tests/test_cases/hologres_test.go
  tablestore-unit-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-tablestore-pipeline
      cancel-in-progress: false
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
        
      - name: Run tablestore unit tests
        env:
          ACCESS_ID: ${{ secrets.SDK_ACCESS_ID }}
          ACCESS_KEY: ${{ secrets.SDK_ACCESS_KEY }}
          SDK_INSTANCE_ID: ${{ secrets.SDK_INSTANCE_ID }}
        run:
          go test -v -count=1 ./tests/test_cases/tablestore_test.go
  