name: gosdk test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

concurrency:
  group: ci-pipeline
  cancel-in-progress: false

jobs:
  featuredb-unit-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        try: [1, 2]  # 模拟最多三次尝试
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0'
        
      - name: Run unit tests
        env:
          ACCESS_ID: ${{ secrets.SDK_ACCESS_ID }}
          ACCESS_KEY: ${{ secrets.SDK_ACCESS_KEY }}
          FEATUREDB_USERNAME: ${{ secrets.FEATUREDB_USERNAME }}
          FEATUREDB_PASSWORD: ${{ secrets.FEATUREDB_PASSWORD }}
          SDK_INSTANCE_ID: ${{ secrets.SDK_INSTANCE_ID }}
          FEATURE_SERVICE_ADDRESS: ${{ secrets.FEATURE_SERVICE_ADDRESS }}
          FEATURE_SERVICE_TOKEN: ${{ secrets.FEATURE_SERVICE_TOKEN }}
        run:
          go test -v -count=1 ./tests/test_cases/featuredb_test.go
  